version: "3"
services:
  clientBot:
    image: client-bot:1.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appoint_me_db
      SPRING_DATASOURCE_USERNAME: commonBotUser
      SPRING_DATASOURCE_PASSWORD: s3cr3TPassW0rd
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/appoint_me_db
      SPRING_FLYWAY_USER: commonBotUser
      SPRING_FLYWAY_PASSWORD: s3cr3TPassW0rd
      TELEGRAM_BOT_NAME: AppointmentMe_bot
      TELEGRAM_BOT_TOKEN: 6141362996:AAEoL9qzbL1IxHyIMttLG0lIKLd8xRyQidg
      TELEGRAM_BOT_WEBHOOK_URL: https://e6cb-5-44-169-37.ngrok.io
      BOT_OWNER_ID: 614644552
      CACHE_CLEANER_ENABLE: true
      CACHE_CLEANER_CRON: 0 0 */2 ? * *
      APPOINTMENTS_TABLE_CLEANER_ENABLE: true
      APPOINTMENTS_TABLE_CLEANER_CRON: 0 0 12 1 * ?
      APPOINTMENTS_TABLE_CLEANER_EXPIRATION_DAYS: 30
      NOTIFY_CLIENTS_ENABLE: true
      NOTIFY_CLIENTS_CRON: 0 * * ? * *
      SERVER_PORT: 8081
    container_name: client-bot
    ports:
      - "8081:8081"
#    restart: always
    depends_on:
      - postgres

  adminBot:
    image: admin-bot:1.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appoint_me_db
      SPRING_DATASOURCE_USERNAME: commonBotUser
      SPRING_DATASOURCE_PASSWORD: s3cr3TPassW0rd
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/appoint_me_db
      SPRING_FLYWAY_USER: commonBotUser
      SPRING_FLYWAY_PASSWORD: s3cr3TPassW0rd
      TELEGRAM_BOT_NAME: AppointmentMe_bot
      TELEGRAM_BOT_TOKEN: 6141362996:AAEoL9qzbL1IxHyIMttLG0lIKLd8xRyQidg
      TELEGRAM_BOT_WEBHOOK_URL: https://e6cb-5-44-169-37.ngrok.io
      SERVER_PORT: 8082
    container_name: adminBot-bot
    ports:
      - "8082:8082"
    #    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:14.9-alpine3.18
    container_name: database
    environment:
      POSTGRES_DB: "appoint_me_db"
      POSTGRES_USER: "commonBotUser"
      POSTGRES_PASSWORD: "s3cr3TPassW0rd"
      PGDATA: "/var/lib/postgresql/data"
#      Проверить, что все сохраняется
    volumes:
      - appoint-me-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commonBotUser -d appoint_me_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:1.25.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt/

  certbot:
    image: certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - etc-letsencrypt:/etc/letsencrypt/
      - www-html:/var/www/html
    command:
      - certonly --webroot --webroot-path=/var/www/html --email dmitry.golcev@gmail.com --agree-tos -no-eff-email -staging -d appointme.ru
    depends_on:
      - nginx

volumes:
  appoint-me-data:
  etc-letsencrypt:
  www-html:
  nginx_config:
